import { cn } from "@Util/shadcn";

const ContainerBgObject = ({ className = "" }) => {
  return (
    <svg
      width="121"
      height="68"
      viewBox="0 0 121 68"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={cn("absolute top-0 left-0", className)}
    >
      <rect
        x="21.5"
        y="-7"
        width="24"
        height="24"
        fill="white"
        fillOpacity="0.05"
      />
      <rect
        x="45.5"
        y="17"
        width="24"
        height="24"
        fill="white"
        fillOpacity="0.05"
      />
      <rect
        x="69.5"
        y="41"
        width="24"
        height="24"
        fill="white"
        fillOpacity="0.05"
      />
      <rect
        x="48.5"
        y="-11"
        width="24"
        height="24"
        fill="white"
        fillOpacity="0.05"
      />
      <rect
        x="72.5"
        y="13"
        width="24"
        height="24"
        fill="white"
        fillOpacity="0.05"
      />
      <rect
        x="96.5"
        y="37"
        width="24"
        height="24"
        fill="white"
        fillOpacity="0.05"
      />
      <rect
        x="-5.5"
        y="-4"
        width="24"
        height="24"
        fill="white"
        fillOpacity="0.05"
      />
      <rect
        x="18.5"
        y="20"
        width="24"
        height="24"
        fill="white"
        fillOpacity="0.05"
      />
      <rect
        x="42.5"
        y="44"
        width="24"
        height="24"
        fill="white"
        fillOpacity="0.05"
      />
    </svg>
  );
};

export default ContainerBgObject;
